#!/usr/bin/env bash
# `make setup`: check prerequisites, fetch the frontend repository if it is missing, and create
# the production settings file (.env.production by default) with freshly generated secrets.
#
# An existing settings file is never overwritten, only checked. Values can be given on the
# command line instead of answering questions:
#   make setup DOMAIN=charge.example.com MAPTILER_KEY=abc123
# Optional: OCPP_DOMAIN (default ocpp.<DOMAIN>), SCHEME=http (no TLS, e.g. before DNS is ready),
# FRONTEND_DIR (default ../charger-fe), FRONTEND_REPO (git URL to clone it from).
set -euo pipefail

cd "$(dirname "$0")/../.."
ROOT="$(pwd)"
ENV_FILE="${ENV_FILE:-.env.production}"
REQUIRED=(DOMAIN PUBLIC_URL PUBLIC_WS_URL SITE_ADDRESS OCPP_SITE_ADDRESS MAPTILER_KEY
          MONGO_ROOT_USER MONGO_ROOT_PASSWORD REDIS_PASSWORD ADMIN_TOKEN
          FRONTEND_DIR FRONTEND_DOCKERFILE)

fail() { echo "setup: $*" >&2; exit 1; }
ok() { echo "  ok  $*"; }

# --- prerequisites ------------------------------------------------------------------------------
echo "Checking prerequisites"
command -v docker >/dev/null || fail "Docker is not installed. Run: make install-docker"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is missing. Run: make install-docker"
docker info >/dev/null 2>&1 || fail "cannot talk to Docker. Is it running, and are you in the 'docker' group? (log out and in after make install-docker)"
command -v git >/dev/null || fail "git is not installed (sudo apt-get install -y git)"
ok "docker $(docker version --format '{{.Server.Version}}'), $(docker compose version --short 2>/dev/null || echo compose)"

# --- an existing settings file: check it and stop ----------------------------------------------
if [ -f "$ENV_FILE" ]; then
  echo "Keeping the existing $ENV_FILE (delete it to start over)"
  # shellcheck disable=SC1090
  set -a; . "$ENV_FILE"; set +a
  for name in "${REQUIRED[@]}"; do
    [ -n "${!name:-}" ] || fail "$ENV_FILE has no value for $name"
  done
  [ -d "$FRONTEND_DIR" ] || fail "FRONTEND_DIR=$FRONTEND_DIR does not exist"
  ok "$ENV_FILE has every required value"
  exit 0
fi

# --- ask for (or take) the few values a human must choose ---------------------------------------
ask() {  # ask NAME "question" [default]
  local name="$1" question="$2" default="${3:-}" value="${!1:-}"
  if [ -z "$value" ] && [ -t 0 ]; then
    read -r -p "$question${default:+ [$default]}: " value
  fi
  value="${value:-$default}"
  [ -n "$value" ] || fail "$name is required: make setup $name=..."
  printf -v "$name" '%s' "$value"
}

secret() { openssl rand -hex 24 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(24))'; }

echo "Creating $ENV_FILE"
ask DOMAIN "Domain for the website and API (DNS A record pointing at this server)"
DOMAIN="${DOMAIN#http://}"; DOMAIN="${DOMAIN#https://}"; DOMAIN="${DOMAIN%%/*}"
ask OCPP_DOMAIN "Domain chargers connect to (OCPP over TLS)" "ocpp.$DOMAIN"
ask MAPTILER_KEY "MapTiler API key (https://cloud.maptiler.com/account/keys/)"
SCHEME="${SCHEME:-https}"
[ "$SCHEME" = https ] || [ "$SCHEME" = http ] || fail "SCHEME must be https or http"
WS_SCHEME=$([ "$SCHEME" = https ] && echo wss || echo ws)
# Caddy obtains a certificate for a bare hostname; an http:// address serves plain HTTP.
ADDRESS_PREFIX=$([ "$SCHEME" = https ] && echo "" || echo "http://")

# --- the frontend repository ---------------------------------------------------------------------
FRONTEND_DIR="${FRONTEND_DIR:-$ROOT/../charger-fe}"
if [ ! -d "$FRONTEND_DIR" ]; then
  FRONTEND_REPO="${FRONTEND_REPO:-git@github.com:danilokujacic/chargers-fe.git}"
  echo "Cloning the frontend from $FRONTEND_REPO into $FRONTEND_DIR"
  git clone "$FRONTEND_REPO" "$FRONTEND_DIR" \
    || fail "could not clone the frontend. Clone it yourself, or set FRONTEND_DIR / FRONTEND_REPO"
fi
FRONTEND_DIR="$(cd "$FRONTEND_DIR" && pwd)"
[ -f "$FRONTEND_DIR/package.json" ] || fail "$FRONTEND_DIR does not look like the charger-fe repository"
ok "frontend at $FRONTEND_DIR"

umask 077
cat > "$ENV_FILE" <<EOF
# Production settings for docker-compose.yml, generated by \`make setup\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Private: it holds the database, Redis and admin passwords. Changing DOMAIN, PUBLIC_URL,
# PUBLIC_WS_URL or MAPTILER_KEY needs a rebuild of the website: make build up
COMPOSE_PROJECT_NAME=chargers

# Public addresses
DOMAIN=$DOMAIN
OCPP_DOMAIN=$OCPP_DOMAIN
PUBLIC_URL=$SCHEME://$DOMAIN
PUBLIC_WS_URL=$WS_SCHEME://$DOMAIN
SITE_ADDRESS=$ADDRESS_PREFIX$DOMAIN
OCPP_SITE_ADDRESS=$ADDRESS_PREFIX$OCPP_DOMAIN
FIRMWARE_BASE_URL=$SCHEME://$OCPP_DOMAIN

# Ports published on this server. Caddy serves 80/443. main.py's own port stays on localhost
# unless chargers must connect without TLS: then CS_BIND=0.0.0.0 (and open CS_PORT).
HTTP_PORT=80
HTTPS_PORT=443
CS_BIND=127.0.0.1
CS_PORT=9000

# Map tiles (public by nature: restrict it to your domain in the MapTiler dashboard)
MAPTILER_KEY=$MAPTILER_KEY

# Secrets, generated
MONGO_ROOT_USER=chargers
MONGO_ROOT_PASSWORD=$(secret)
MONGODB_DB=ocpp_poc
REDIS_PASSWORD=$(secret)
ADMIN_TOKEN=$(secret)

# Where the frontend repository is, and how to build it
FRONTEND_DIR=$FRONTEND_DIR
FRONTEND_DOCKERFILE=$ROOT/deploy/frontend.Dockerfile
EOF
chmod 600 "$ENV_FILE"
ok "wrote $ENV_FILE (mode 600)"
cat <<EOF

Next:
  1. Point DNS for $DOMAIN and $OCPP_DOMAIN at this server, and open ports 80 and 443.
  2. make deploy      # build, start, migrate, load the PlugShare sites
EOF
